#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

exec 1>&2

FILES_PATTERN='\.(ts)(\..+)?$'
FORBIDDEN='console\.[dir|log|info|warn]'

#check for console. references in your code

if git diff --cached --name-only | \
    grep -E $FILES_PATTERN | \
    xargs grep --with-filename -n $FORBIDDEN | \
    grep -v '//';
then
    echo -e "\n${red} Dính console rồi, xóa đi cụ nhé.\n${no_color}"
    exit 1;
else
    npx lint-staged
fi
